require("express-async-errors")
const express = require("express")
const checkConfig = require("./src/start/checkConfig")
const startDB = require("./src/start/startDB")
const startErrorMiddleware = require("./src/start/startErrorMiddleware")
const startListen = require("./src/start/startListen")
const startMiddleware = require("./src/start/startMiddleware")
const startRoutes = require("./src/start/startRoutes")

checkConfig()
const app = express()
startDB()
startMiddleware(app)
startRoutes(app)
startListen(app)
startErrorMiddleware(app)
